#!/bin/bash

barf() {
echo ::::::::::::::::$1 | tee -a $LOG
}

barf "starting jackd..."
jackd -R -d alsa -d "$CARD" -p $PERIOD >> $LOG 2>&1 &
barf "started."

sleep 2

barf "starting zita-j2n..."
zita-j2n $MCAST $PORT $IFACE >> $LOG 2>&1 &
barf "started."

sleep 2

barf "connecting ports..."
jack_connect system:capture_1 zita-j2n:in_1 >> $LOG 2>&1 
jack_connect system:capture_2 zita-j2n:in_2 >> $LOG 2>&1 
barf "connected."

# kill: pkill jackd
