#!/bin/bash

source /opt/ipaudio/vars.sh

if [[ $ROLE = 'server' ]]; then
	echo starting server
	exec /opt/ipaudio/ipaudio_server
elif [[ $ROLE = 'client' ]]; then
	echo starting client
	exec /opt/ipaudio/ipaudio_client
fi
